### ISSUE TITLE
Enable searching by wof:id

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/go-whosonfirst-spelunker-httpd#18]
https://spelunker.whosonfirst.org/search?q=85633345

Previously, searching a wof:id would result in that WOF record loading in the Spelunker: https://spelunker.whosonfirst.org/id/85633345/. Now, I see a search resulting in "There are no places."

**Comment by thisisaaronland** [comment]
Note(s) to self: It would be nice(r) not to have to specify this kind of behaviour in each database implementation. Perhaps an alternative approach would be to have the web application fire off an addition `/id/{ID}/geojson` request if the query string looks like a WOF ID.

**Comment by thisisaaronland** [comment]
Notes to self: This could happen in `search.go` rather than JavaScript because a) we're not using JS for search b) search shouldn't depend on JS c) doing it in Go would allow us to use channels to manage async queries:

https://github.com/whosonfirst/go-whosonfirst-spelunker-httpd/blob/main/www/search.go#L83-L114

This would require recalculating pagination results.

**Comment by thisisaaronland** [comment]
Notes to self: Don't bother integrating any features whose ID matches the query string in to the default query pagination. Simply return it as a separate template variable and always include at the top of the list.

**Comment by straup** [comment]
Fixed: https://spelunker.whosonfirst.org/search?q=102555229
