### ISSUE TITLE
Search by WOF ID results displayed at Null Island

### ISSUE THREAD

**Issue by thisisaaronland** [whosonfirst/go-whosonfirst-spelunker-httpd#22]
https://spelunker.whosonfirst.org/search?q=102527513

**Comment by straup** [comment]
That's because the template is doing this:

```
<li class="spr-place" data-latitude="{{ .Feature.Latitude }}" data-longitude="{{ .Feature.Longitude }}" style="margin-bottom:.5rem;">
```

Where those properties don't exist. Options include:

* Make a template function for deriving the centroid for `{{ .Feature }}` (see also: `go-whosonfirst-feature/properties`)
* Converting the feature in to an SPR because passing it down to the template. I feel like I tried to do this and something something something?

**Comment by straup** [comment]
`{{ .Feature }}` _is_ an SPR and the lat/lon data attributes are correct so... JavaScript?
```
<li class="spr-place" data-latitude="37.61799" data-longitude="-122.370943" style="margin-bottom:.5rem;">
```
